// Deterministic UUIDs for consistent foreign key relationships
export const DEMO_IDS = {
  // Users
  seller1: "d0000001-0000-0000-0000-000000000001",
  seller2: "d0000001-0000-0000-0000-000000000002",
  buyer1: "d0000002-0000-0000-0000-000000000001",
  buyer2: "d0000002-0000-0000-0000-000000000002",
  agent1: "d0000003-0000-0000-0000-000000000001",
  admin1: "d0000004-0000-0000-0000-000000000001",
  // Listings
  listing1: "d1000001-0000-0000-0000-000000000001",
  listing2: "d1000001-0000-0000-0000-000000000002",
  listing3: "d1000001-0000-0000-0000-000000000003",
  listing4: "d1000001-0000-0000-0000-000000000004",
  listing5: "d1000001-0000-0000-0000-000000000005",
  listing6: "d1000001-0000-0000-0000-000000000006",
  listing7: "d1000001-0000-0000-0000-000000000007",
  listing8: "d1000001-0000-0000-0000-000000000008",
  // Searches
  search1: "d2000001-0000-0000-0000-000000000001",
  search2: "d2000001-0000-0000-0000-000000000002",
  search3: "d2000001-0000-0000-0000-000000000003",
  // Matches
  match1: "d3000001-0000-0000-0000-000000000001",
  match2: "d3000001-0000-0000-0000-000000000002",
  match3: "d3000001-0000-0000-0000-000000000003",
  match4: "d3000001-0000-0000-0000-000000000004",
  match5: "d3000001-0000-0000-0000-000000000005",
  // Inquiries
  inquiry1: "d4000001-0000-0000-0000-000000000001",
  inquiry2: "d4000001-0000-0000-0000-000000000002",
  inquiry3: "d4000001-0000-0000-0000-000000000003",
};

function daysAgo(n: number) {
  return new Date(Date.now() - n * 86400000).toISOString();
}

function daysFromNow(n: number) {
  return new Date(Date.now() + n * 86400000).toISOString().split("T")[0];
}

// ─── PROFILES ────────────────────────────────────────────
export const MOCK_PROFILES = [
  {
    id: DEMO_IDS.seller1,
    role: "seller",
    first_name: "Maria",
    last_name: "Gonzalez",
    email: "maria@demo.com",
    phone: "(831) 555-0101",
    created_at: daysAgo(45),
    updated_at: daysAgo(2),
  },
  {
    id: DEMO_IDS.seller2,
    role: "seller",
    first_name: "James",
    last_name: "Park",
    email: "james@demo.com",
    phone: "(831) 555-0102",
    created_at: daysAgo(30),
    updated_at: daysAgo(5),
  },
  {
    id: DEMO_IDS.buyer1,
    role: "buyer",
    first_name: "Rachel",
    last_name: "Kim",
    email: "rachel@demo.com",
    phone: "(408) 555-0201",
    created_at: daysAgo(20),
    updated_at: daysAgo(1),
  },
  {
    id: DEMO_IDS.buyer2,
    role: "buyer",
    first_name: "David",
    last_name: "Thompson",
    email: "david@demo.com",
    phone: "(510) 555-0202",
    created_at: daysAgo(15),
    updated_at: daysAgo(3),
  },
  {
    id: DEMO_IDS.agent1,
    role: "agent",
    first_name: "Sarah",
    last_name: "Chen",
    email: "sarah@demo.com",
    phone: "(831) 555-0301",
    created_at: daysAgo(90),
    updated_at: daysAgo(1),
  },
  {
    id: DEMO_IDS.admin1,
    role: "admin",
    first_name: "Admin",
    last_name: "User",
    email: "admin@demo.com",
    phone: null,
    created_at: daysAgo(120),
    updated_at: daysAgo(0),
  },
];

// ─── AGENTS ──────────────────────────────────────────────
export const MOCK_AGENTS = [
  {
    id: DEMO_IDS.agent1,
    license_number: "DRE-02198745",
    license_state: "CA",
    brokerage: "Coastal Realty Group",
    markets: ["Monterey", "Carmel-by-the-Sea", "Pacific Grove"],
    bio: "15+ years helping families find their dream homes on the Monterey Peninsula. Specializing in pre-market opportunities and first-time buyers.",
    headshot_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&h=200&fit=crop&crop=face",
    is_verified: true,
    subscription_status: "active",
    subscription_tier: "pro",
    created_at: daysAgo(90),
    updated_at: daysAgo(1),
    profiles: {
      first_name: "Sarah",
      last_name: "Chen",
      email: "sarah@demo.com",
    },
  },
];

// ─── LISTING PHOTOS (Unsplash — free to use) ────────────
const PHOTOS = {
  [DEMO_IDS.listing1]: [
    { id: "p1a", listing_id: DEMO_IDS.listing1, storage_path: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop", display_order: 0, created_at: daysAgo(40) },
    { id: "p1b", listing_id: DEMO_IDS.listing1, storage_path: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", display_order: 1, created_at: daysAgo(40) },
  ],
  [DEMO_IDS.listing2]: [
    { id: "p2a", listing_id: DEMO_IDS.listing2, storage_path: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", display_order: 0, created_at: daysAgo(28) },
  ],
  [DEMO_IDS.listing3]: [
    { id: "p3a", listing_id: DEMO_IDS.listing3, storage_path: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", display_order: 0, created_at: daysAgo(18) },
    { id: "p3b", listing_id: DEMO_IDS.listing3, storage_path: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop", display_order: 1, created_at: daysAgo(18) },
  ],
  [DEMO_IDS.listing4]: [
    { id: "p4a", listing_id: DEMO_IDS.listing4, storage_path: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop", display_order: 0, created_at: daysAgo(12) },
  ],
  [DEMO_IDS.listing5]: [
    { id: "p5a", listing_id: DEMO_IDS.listing5, storage_path: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop", display_order: 0, created_at: daysAgo(8) },
  ],
  [DEMO_IDS.listing6]: [
    { id: "p6a", listing_id: DEMO_IDS.listing6, storage_path: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop", display_order: 0, created_at: daysAgo(6) },
    { id: "p6b", listing_id: DEMO_IDS.listing6, storage_path: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop", display_order: 1, created_at: daysAgo(6) },
  ],
  [DEMO_IDS.listing7]: [
    { id: "p7a", listing_id: DEMO_IDS.listing7, storage_path: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop", display_order: 0, created_at: daysAgo(4) },
  ],
  [DEMO_IDS.listing8]: [
    { id: "p8a", listing_id: DEMO_IDS.listing8, storage_path: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop", display_order: 0, created_at: daysAgo(2) },
  ],
};

// ─── LISTINGS ────────────────────────────────────────────
export const MOCK_LISTINGS = [
  {
    id: DEMO_IDS.listing1,
    seller_id: DEMO_IDS.seller1,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "active",
    property_type: "single_family",
    asking_price: 1195000,
    city: "Pacific Grove",
    state: "CA",
    zip: "93950",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2450,
    lot_sqft: 6800,
    year_built: 1952,
    description: "Beautifully updated Craftsman with ocean views from the upstairs primary suite. Original hardwood floors, chef's kitchen with marble counters, and a sun-drenched backyard with mature fruit trees. Walking distance to Lover's Point.",
    preferred_move_date: daysFromNow(90),
    move_flexibility: "flexible",
    view_count: 142,
    save_count: 18,
    inquiry_count: 5,
    created_at: daysAgo(40),
    updated_at: daysAgo(2),
    listing_photos: PHOTOS[DEMO_IDS.listing1],
  },
  {
    id: DEMO_IDS.listing2,
    seller_id: DEMO_IDS.seller1,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "active",
    property_type: "condo",
    asking_price: 649000,
    city: "Monterey",
    state: "CA",
    zip: "93940",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1180,
    lot_sqft: null,
    year_built: 2008,
    description: "Modern condo in the heart of downtown Monterey. Open floor plan, in-unit laundry, one covered parking space. HOA includes pool, gym, and rooftop deck with bay views.",
    preferred_move_date: daysFromNow(45),
    move_flexibility: "rigid",
    view_count: 89,
    save_count: 12,
    inquiry_count: 3,
    created_at: daysAgo(28),
    updated_at: daysAgo(5),
    listing_photos: PHOTOS[DEMO_IDS.listing2],
  },
  {
    id: DEMO_IDS.listing3,
    seller_id: DEMO_IDS.seller2,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "active",
    property_type: "single_family",
    asking_price: 1850000,
    city: "Carmel-by-the-Sea",
    state: "CA",
    zip: "93921",
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2100,
    lot_sqft: 5200,
    year_built: 1938,
    description: "Classic Carmel cottage with storybook charm. Stone fireplace, exposed beam ceilings, and a private garden courtyard. Steps from Ocean Avenue galleries and restaurants.",
    preferred_move_date: daysFromNow(120),
    move_flexibility: "very_flexible",
    view_count: 234,
    save_count: 31,
    inquiry_count: 8,
    created_at: daysAgo(18),
    updated_at: daysAgo(3),
    listing_photos: PHOTOS[DEMO_IDS.listing3],
  },
  {
    id: DEMO_IDS.listing4,
    seller_id: DEMO_IDS.seller2,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "active",
    property_type: "single_family",
    asking_price: 975000,
    city: "Seaside",
    state: "CA",
    zip: "93955",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1650,
    lot_sqft: 5500,
    year_built: 1975,
    description: "Remodeled ranch-style home with an open layout and vaulted ceilings. New roof, updated electrical, and a spacious two-car garage. Great neighborhood close to schools and shopping.",
    preferred_move_date: daysFromNow(60),
    move_flexibility: "flexible",
    view_count: 67,
    save_count: 8,
    inquiry_count: 2,
    created_at: daysAgo(12),
    updated_at: daysAgo(1),
    listing_photos: PHOTOS[DEMO_IDS.listing4],
  },
  {
    id: DEMO_IDS.listing5,
    seller_id: DEMO_IDS.seller1,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "active",
    property_type: "townhouse",
    asking_price: 785000,
    city: "Marina",
    state: "CA",
    zip: "93933",
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1820,
    lot_sqft: 2400,
    year_built: 2019,
    description: "Nearly new townhome in the Dunes community. Smart home features, energy-efficient design, and a private rooftop terrace with panoramic views. Community pool and parks.",
    preferred_move_date: daysFromNow(30),
    move_flexibility: "rigid",
    view_count: 53,
    save_count: 6,
    inquiry_count: 1,
    created_at: daysAgo(8),
    updated_at: daysAgo(1),
    listing_photos: PHOTOS[DEMO_IDS.listing5],
  },
  {
    id: DEMO_IDS.listing6,
    seller_id: DEMO_IDS.seller2,
    assigned_agent_id: null,
    status: "active",
    property_type: "single_family",
    asking_price: 2350000,
    city: "Pebble Beach",
    state: "CA",
    zip: "93953",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3800,
    lot_sqft: 12000,
    year_built: 1985,
    description: "Elegant estate on a quiet cul-de-sac near the Lodge. Soaring ceilings, chef's kitchen, wine cellar, and a resort-style backyard with heated pool and spa. Golf course views.",
    preferred_move_date: daysFromNow(180),
    move_flexibility: "very_flexible",
    view_count: 312,
    save_count: 45,
    inquiry_count: 11,
    created_at: daysAgo(6),
    updated_at: daysAgo(1),
    listing_photos: PHOTOS[DEMO_IDS.listing6],
  },
  {
    id: DEMO_IDS.listing7,
    seller_id: DEMO_IDS.seller1,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "draft",
    property_type: "multi_family",
    asking_price: 1450000,
    city: "Monterey",
    state: "CA",
    zip: "93940",
    bedrooms: 6,
    bathrooms: 4,
    sqft: 3200,
    lot_sqft: 7500,
    year_built: 1960,
    description: "Duplex investment property — two 3BR/2BA units, both currently leased with excellent tenants. Separately metered, recent plumbing and HVAC upgrades. Strong rental history.",
    preferred_move_date: daysFromNow(150),
    move_flexibility: "very_flexible",
    view_count: 28,
    save_count: 4,
    inquiry_count: 0,
    created_at: daysAgo(4),
    updated_at: daysAgo(0),
    listing_photos: PHOTOS[DEMO_IDS.listing7],
  },
  {
    id: DEMO_IDS.listing8,
    seller_id: DEMO_IDS.seller2,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "active",
    property_type: "land",
    asking_price: 425000,
    city: "Carmel Valley",
    state: "CA",
    zip: "93924",
    bedrooms: null,
    bathrooms: null,
    sqft: null,
    lot_sqft: 43560,
    year_built: null,
    description: "One-acre parcel with approved building plans in sunny Carmel Valley. Well and septic already in place. Oak-studded hillside with valley views. Ready to build your dream home.",
    preferred_move_date: daysFromNow(365),
    move_flexibility: "very_flexible",
    view_count: 41,
    save_count: 7,
    inquiry_count: 2,
    created_at: daysAgo(2),
    updated_at: daysAgo(0),
    listing_photos: PHOTOS[DEMO_IDS.listing8],
  },
];

// ─── BUYER SEARCHES ──────────────────────────────────────
export const MOCK_BUYER_SEARCHES = [
  {
    id: DEMO_IDS.search1,
    buyer_id: DEMO_IDS.buyer1,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "active",
    cities: ["Pacific Grove", "Monterey", "Seaside"],
    min_price: 500000,
    max_price: 1300000,
    property_types: ["single_family", "townhouse"],
    min_bedrooms: 3,
    min_bathrooms: 2,
    preferred_move_date: daysFromNow(90),
    move_flexibility: "flexible",
    created_at: daysAgo(20),
    updated_at: daysAgo(1),
  },
  {
    id: DEMO_IDS.search2,
    buyer_id: DEMO_IDS.buyer2,
    assigned_agent_id: DEMO_IDS.agent1,
    status: "active",
    cities: ["Carmel-by-the-Sea", "Carmel Valley", "Pebble Beach"],
    min_price: 1000000,
    max_price: 2500000,
    property_types: ["single_family"],
    min_bedrooms: 3,
    min_bathrooms: 2,
    preferred_move_date: daysFromNow(180),
    move_flexibility: "very_flexible",
    created_at: daysAgo(15),
    updated_at: daysAgo(3),
  },
  {
    id: DEMO_IDS.search3,
    buyer_id: DEMO_IDS.buyer1,
    assigned_agent_id: null,
    status: "active",
    cities: ["Monterey"],
    min_price: 400000,
    max_price: 700000,
    property_types: ["condo"],
    min_bedrooms: 2,
    min_bathrooms: 1,
    preferred_move_date: daysFromNow(45),
    move_flexibility: "rigid",
    created_at: daysAgo(10),
    updated_at: daysAgo(1),
  },
];

// ─── MATCHES ─────────────────────────────────────────────
export const MOCK_MATCHES = [
  {
    id: DEMO_IDS.match1,
    listing_id: DEMO_IDS.listing1,
    buyer_search_id: DEMO_IDS.search1,
    handling_agent_id: DEMO_IDS.agent1,
    match_score: 92,
    status: "interested",
    match_factors: { price: 28, location: 25, timeline: 22, specs: 12, type: 5 },
    created_at: daysAgo(18),
    updated_at: daysAgo(2),
    // Joined relations
    listings: MOCK_LISTINGS[0],
    buyer_searches: { buyer_id: DEMO_IDS.buyer1 },
  },
  {
    id: DEMO_IDS.match2,
    listing_id: DEMO_IDS.listing4,
    buyer_search_id: DEMO_IDS.search1,
    handling_agent_id: DEMO_IDS.agent1,
    match_score: 78,
    status: "new",
    match_factors: { price: 25, location: 20, timeline: 18, specs: 12, type: 3 },
    created_at: daysAgo(10),
    updated_at: daysAgo(1),
    listings: MOCK_LISTINGS[3],
    buyer_searches: { buyer_id: DEMO_IDS.buyer1 },
  },
  {
    id: DEMO_IDS.match3,
    listing_id: DEMO_IDS.listing3,
    buyer_search_id: DEMO_IDS.search2,
    handling_agent_id: DEMO_IDS.agent1,
    match_score: 85,
    status: "contacted",
    match_factors: { price: 26, location: 25, timeline: 20, specs: 10, type: 4 },
    created_at: daysAgo(12),
    updated_at: daysAgo(3),
    listings: MOCK_LISTINGS[2],
    buyer_searches: { buyer_id: DEMO_IDS.buyer2 },
  },
  {
    id: DEMO_IDS.match4,
    listing_id: DEMO_IDS.listing6,
    buyer_search_id: DEMO_IDS.search2,
    handling_agent_id: null,
    match_score: 55,
    status: "new",
    match_factors: { price: 15, location: 20, timeline: 10, specs: 8, type: 2 },
    created_at: daysAgo(5),
    updated_at: daysAgo(1),
    listings: MOCK_LISTINGS[5],
    buyer_searches: { buyer_id: DEMO_IDS.buyer2 },
  },
  {
    id: DEMO_IDS.match5,
    listing_id: DEMO_IDS.listing2,
    buyer_search_id: DEMO_IDS.search3,
    handling_agent_id: DEMO_IDS.agent1,
    match_score: 88,
    status: "closed_won",
    match_factors: { price: 28, location: 25, timeline: 20, specs: 10, type: 5 },
    created_at: daysAgo(25),
    updated_at: daysAgo(8),
    listings: MOCK_LISTINGS[1],
    buyer_searches: { buyer_id: DEMO_IDS.buyer1 },
  },
];

// ─── INQUIRIES ───────────────────────────────────────────
export const MOCK_INQUIRIES = [
  {
    id: DEMO_IDS.inquiry1,
    listing_id: DEMO_IDS.listing1,
    buyer_id: DEMO_IDS.buyer1,
    agent_id: DEMO_IDS.agent1,
    inquiry_type: "schedule_tour",
    message: "Hi, I'd love to see this property this weekend if possible. The ocean views sound amazing!",
    status: "new",
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    listings: MOCK_LISTINGS[0],
    profiles: MOCK_PROFILES[2], // Rachel Kim (buyer1)
  },
  {
    id: DEMO_IDS.inquiry2,
    listing_id: DEMO_IDS.listing3,
    buyer_id: DEMO_IDS.buyer2,
    agent_id: DEMO_IDS.agent1,
    inquiry_type: "general_question",
    message: "What's the HOA situation? Also curious about the garden courtyard dimensions.",
    status: "responded",
    created_at: daysAgo(8),
    updated_at: daysAgo(6),
    listings: MOCK_LISTINGS[2],
    profiles: MOCK_PROFILES[3], // David Thompson (buyer2)
  },
  {
    id: DEMO_IDS.inquiry3,
    listing_id: DEMO_IDS.listing4,
    buyer_id: DEMO_IDS.buyer1,
    agent_id: DEMO_IDS.agent1,
    inquiry_type: "make_offer",
    message: "We're very interested in this property. Would like to discuss offer terms.",
    status: "agent_notified",
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    listings: MOCK_LISTINGS[3],
    profiles: MOCK_PROFILES[2], // Rachel Kim
  },
];

// ─── SAVED LISTINGS ──────────────────────────────────────
export const MOCK_SAVED_LISTINGS = [
  {
    id: "s1",
    buyer_id: DEMO_IDS.buyer1,
    listing_id: DEMO_IDS.listing1,
    created_at: daysAgo(15),
    listings: MOCK_LISTINGS[0],
  },
  {
    id: "s2",
    buyer_id: DEMO_IDS.buyer1,
    listing_id: DEMO_IDS.listing3,
    created_at: daysAgo(10),
    listings: MOCK_LISTINGS[2],
  },
  {
    id: "s3",
    buyer_id: DEMO_IDS.buyer2,
    listing_id: DEMO_IDS.listing6,
    created_at: daysAgo(4),
    listings: MOCK_LISTINGS[5],
  },
];

// ─── HELPER: Get demo user by role ───────────────────────
export function getDemoUser(role: string) {
  switch (role) {
    case "seller":
      return { id: DEMO_IDS.seller1, email: "maria@demo.com", user_metadata: { first_name: "Maria", last_name: "Gonzalez", role: "seller" } };
    case "buyer":
      return { id: DEMO_IDS.buyer1, email: "rachel@demo.com", user_metadata: { first_name: "Rachel", last_name: "Kim", role: "buyer" } };
    case "agent":
      return { id: DEMO_IDS.agent1, email: "sarah@demo.com", user_metadata: { first_name: "Sarah", last_name: "Chen", role: "agent" } };
    case "admin":
      return { id: DEMO_IDS.admin1, email: "admin@demo.com", user_metadata: { first_name: "Admin", last_name: "User", role: "admin" } };
    default:
      return { id: DEMO_IDS.buyer1, email: "rachel@demo.com", user_metadata: { first_name: "Rachel", last_name: "Kim", role: "buyer" } };
  }
}

// ─── ALL MOCK DATA BY TABLE NAME ─────────────────────────
export const MOCK_TABLES: Record<string, Record<string, unknown>[]> = {
  profiles: MOCK_PROFILES,
  agents: MOCK_AGENTS,
  listings: MOCK_LISTINGS,
  listing_photos: Object.values(PHOTOS).flat(),
  buyer_searches: MOCK_BUYER_SEARCHES,
  matches: MOCK_MATCHES,
  inquiries: MOCK_INQUIRIES,
  saved_listings: MOCK_SAVED_LISTINGS,
  lender_referrals: [],
  contractor_referrals: [],
  investor_profiles: [],
};
